import { DMEntry, DMStats } from "./types";

// Mock DM entries for the last 30 days
export const mockDMEntries: DMEntry[] = [
  {
    id: "1",
    date: "2026-02-23",
    day: "Sunday",
    platform: "facebook",
    chatsStarted: 25,
    activeChats: 18,
    triageBooked: 8,
    triageShowUp: 6,
    strategyBooked: 4,
    strategyShowUp: 3,
    wins: 2,
    nurture: 7,
    connectStage: 10,
    qualifyStage: 5,
    convertStage: 3,
  },
  {
    id: "2",
    date: "2026-02-23",
    day: "Sunday",
    platform: "instagram",
    chatsStarted: 30,
    activeChats: 22,
    triageBooked: 10,
    triageShowUp: 8,
    strategyBooked: 5,
    strategyShowUp: 4,
    wins: 3,
    nurture: 9,
    connectStage: 12,
    qualifyStage: 6,
    convertStage: 4,
  },
  {
    id: "3",
    date: "2026-02-22",
    day: "Saturday",
    platform: "facebook",
    chatsStarted: 28,
    activeChats: 20,
    triageBooked: 9,
    triageShowUp: 7,
    strategyBooked: 5,
    strategyShowUp: 4,
    wins: 2,
    nurture: 8,
    connectStage: 11,
    qualifyStage: 6,
    convertStage: 3,
  },
  {
    id: "4",
    date: "2026-02-22",
    day: "Saturday",
    platform: "instagram",
    chatsStarted: 32,
    activeChats: 24,
    triageBooked: 11,
    triageShowUp: 9,
    strategyBooked: 6,
    strategyShowUp: 5,
    wins: 3,
    nurture: 10,
    connectStage: 13,
    qualifyStage: 7,
    convertStage: 4,
  },
  {
    id: "5",
    date: "2026-02-21",
    day: "Friday",
    platform: "facebook",
    chatsStarted: 22,
    activeChats: 16,
    triageBooked: 7,
    triageShowUp: 5,
    strategyBooked: 3,
    strategyShowUp: 2,
    wins: 1,
    nurture: 6,
    connectStage: 9,
    qualifyStage: 4,
    convertStage: 3,
  },
  {
    id: "6",
    date: "2026-02-21",
    day: "Friday",
    platform: "instagram",
    chatsStarted: 27,
    activeChats: 19,
    triageBooked: 9,
    triageShowUp: 7,
    strategyBooked: 4,
    strategyShowUp: 3,
    wins: 2,
    nurture: 8,
    connectStage: 10,
    qualifyStage: 5,
    convertStage: 4,
  },
];

// Calculate aggregated stats
function calculateDMStats(platform: "facebook" | "instagram"): DMStats {
  const entries = mockDMEntries.filter((e) => e.platform === platform);

  const totals = entries.reduce(
    (acc, entry) => ({
      chatsStarted: acc.chatsStarted + entry.chatsStarted,
      activeChats: acc.activeChats + entry.activeChats,
      triageBooked: acc.triageBooked + entry.triageBooked,
      triageShowUp: acc.triageShowUp + entry.triageShowUp,
      strategyBooked: acc.strategyBooked + entry.strategyBooked,
      strategyShowUp: acc.strategyShowUp + entry.strategyShowUp,
      wins: acc.wins + entry.wins,
      nurture: acc.nurture + entry.nurture,
    }),
    {
      chatsStarted: 0,
      activeChats: 0,
      triageBooked: 0,
      triageShowUp: 0,
      strategyBooked: 0,
      strategyShowUp: 0,
      wins: 0,
      nurture: 0,
    }
  );

  return {
    platform,
    totalChatsStarted: totals.chatsStarted,
    totalActiveChats: totals.activeChats,
    totalTriageBooked: totals.triageBooked,
    totalTriageShowUp: totals.triageShowUp,
    totalStrategyBooked: totals.strategyBooked,
    totalStrategyShowUp: totals.strategyShowUp,
    totalWins: totals.wins,
    totalNurture: totals.nurture,
    conversionRate: totals.chatsStarted > 0 ? (totals.wins / totals.chatsStarted) * 100 : 0,
    triageShowRate: totals.triageBooked > 0 ? (totals.triageShowUp / totals.triageBooked) * 100 : 0,
    strategyShowRate: totals.strategyBooked > 0 ? (totals.strategyShowUp / totals.strategyBooked) * 100 : 0,
  };
}

export const mockDMStats: DMStats[] = [
  calculateDMStats("facebook"),
  calculateDMStats("instagram"),
];
